// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/home/data/models/song_box_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5928305640102577697),
    name: 'SongBoxEntity',
    lastPropertyId: const obx_int.IdUid(7, 3181102905827924041),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8624885225803337490),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7586400724920189824),
        name: 'serverId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2911008634845642636),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3122654654002831769),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6734461907293903189),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6253127027181774923),
        name: 'album',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 650306154285163447),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3181102905827924041),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5928305640102577697),
    lastIndexId: const obx_int.IdUid(1, 2911008634845642636),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SongBoxEntity: obx_int.EntityDefinition<SongBoxEntity>(
      model: _entities[0],
      toOneRelations: (SongBoxEntity object) => [],
      toManyRelations: (SongBoxEntity object) => {},
      getId: (SongBoxEntity object) => object.id,
      setId: (SongBoxEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SongBoxEntity object, fb.Builder fbb) {
        final serverIdOffset = fbb.writeString(object.serverId);
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        final albumOffset = fbb.writeString(object.album);
        final urlOffset = fbb.writeString(object.url);
        final coverUrlOffset = object.coverUrl == null
            ? null
            : fbb.writeString(object.coverUrl!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serverIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, artistOffset);
        fbb.addOffset(4, albumOffset);
        fbb.addOffset(5, urlOffset);
        fbb.addOffset(6, coverUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final albumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final coverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = SongBoxEntity(
          id: idParam,
          serverId: serverIdParam,
          title: titleParam,
          artist: artistParam,
          album: albumParam,
          url: urlParam,
          coverUrl: coverUrlParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SongBoxEntity] entity fields to define ObjectBox queries.
class SongBoxEntity_ {
  /// See [SongBoxEntity.id].
  static final id = obx.QueryIntegerProperty<SongBoxEntity>(
    _entities[0].properties[0],
  );

  /// See [SongBoxEntity.serverId].
  static final serverId = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[1],
  );

  /// See [SongBoxEntity.title].
  static final title = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[2],
  );

  /// See [SongBoxEntity.artist].
  static final artist = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[3],
  );

  /// See [SongBoxEntity.album].
  static final album = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[4],
  );

  /// See [SongBoxEntity.url].
  static final url = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[5],
  );

  /// See [SongBoxEntity.coverUrl].
  static final coverUrl = obx.QueryStringProperty<SongBoxEntity>(
    _entities[0].properties[6],
  );
}
